version: "3.9"
services:

  dns:
    image: def38/bank-dns:${DEF38_DNS_VERSION}
    dns:
      - 192.168.42.7
    networks:
      simulated:
        ipv4_address: 192.168.42.7

  web:
    image: def38/bank-web:${DEF38_WEB_VERSION}
    dns:
      - 192.168.42.7
    networks:
      simulated:
        ipv4_address: 192.168.42.2

  api:
    image: def38/bank-api:${DEF38_API_VERSION}
    dns:
      - 192.168.42.7
    networks:
      simulated:
        ipv4_address: 192.168.42.3

  test:
    image: def38/bank-test:${DEF38_TEST_VERSION}
    dns:
      - 192.168.42.7
    networks:
      simulated:
        ipv4_address: 192.168.42.4

  swift:
    image: def38/bank-swift:${DEF38_SWIFT_VERSION}
    dns:
      - 192.168.42.7
    networks:
      simulated:
        ipv4_address: 192.168.42.5

  cli:
    image: def38/bank-cli:${DEF38_CLI_VERSION}
    dns:
      - 192.168.42.7
    networks:
      simulated:
        ipv4_address: 192.168.42.6

networks:
  simulated:
    ipam:
      config:
        - subnet: 192.168.42.0/24
          gateway: 192.168.42.1
