version: "3.9"
services:

  web:
    image: def38/bank-web:${DEF38_WEB_VERSION}
    dns:
      - 192.168.42.7
    networks:
      simulated:
        ipv4_address: 192.168.42.2

networks:
  simulated:
    ipam:
      config:
        - subnet: 192.168.42.0/24
          gateway: 192.168.42.1
